import type { ExportedHandler } from "@cloudflare/workers-types";

// @ts-ignore .open-next/worker.js is generated by the Cloudflare build.
import handler from "./.open-next/worker.js";

export { BetterAuthDurableObject } from "better-auth-cloudflare/durable-object";

export default {
    fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
